version: '3.8'

services:
  # Express Server
  app:
    build:
      context: .
      dockerfile: Dockerfile # Assuming the Dockerfile is in the same directory
    container_name: express-app
    ports:
      - '3000:3000'  # Map host port 3000 to container port 3000
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgres://postgres:postgres@db:5432/mydatabase  # PostgreSQL connection string
      - REDIS_URL=redis://redis:6379
    depends_on:
      - db  # The Express app depends on the db service (PostgreSQL)
      - redis  # The Express app depends on the Redis service

  # PostgreSQL Database
  db:
    image: postgres:13
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydatabase  # Default database name
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'  # Map host port 5432 to container port 5432

  # Redis Cache (using Alpine version)
  redis:
    image: redis:alpine
    container_name: redis-cache
    ports:
      - '6379:6379'  # Map host port 6379 to container port 6379
    volumes:
      - redis_data:/data

  # pgAdmin (PostgreSQL admin interface)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com  # Default email to log into pgAdmin
      PGADMIN_DEFAULT_PASSWORD: admin  # Default password for pgAdmin
    ports:
      - '8080:80'  # Map host port 8080 to container port 80 (pgAdmin interface)
    depends_on:
      - db  # pgAdmin depends on PostgreSQL
    volumes:
      - pgadmin_data:/var/lib/pgadmin

volumes:
  postgres_data:
  redis_data:
  pgadmin_data:
